/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comunicacaoserial;

/**
 *
 * @author JoseCarlos
 */
public class Painel extends javax.swing.JFrame {
    Arduino conn = new Arduino();
    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Liga_Led = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        Desliga_Led = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Liga_Led.setMnemonic('1');
        Liga_Led.setText("Ligar");
        Liga_Led.setToolTipText("Liga o led");
        Liga_Led.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Liga_LedMouseClicked(evt);
            }
        });
        Liga_Led.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Liga_LedActionPerformed(evt);
            }
        });

        Fechar.setMnemonic('3');
        Fechar.setText("Fechar");
        Fechar.setToolTipText("Fecha Programa");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });

        Desliga_Led.setMnemonic('2');
        Desliga_Led.setText("Desligar");
        Desliga_Led.setToolTipText("Desliga led");
        Desliga_Led.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Desliga_LedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fechar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Liga_Led)
                        .addGap(18, 18, 18)
                        .addComponent(Desliga_Led)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Liga_Led)
                    .addComponent(Desliga_Led))
                .addGap(46, 46, 46)
                .addComponent(Fechar)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Liga_LedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Liga_LedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Liga_LedActionPerformed

    private void Liga_LedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Liga_LedMouseClicked
        // TODO add your handling code here:
        conn.EnviarArduino(Liga_Led);
    }//GEN-LAST:event_Liga_LedMouseClicked

    private void Desliga_LedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Desliga_LedMouseClicked
        // TODO add your handling code here:
        conn.EnviarArduino(Desliga_Led);
    }//GEN-LAST:event_Desliga_LedMouseClicked

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
        // TODO add your handling code here:
        conn.EnviarArduino(Fechar);
        System.exit(0);
    }//GEN-LAST:event_FecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desliga_Led;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Liga_Led;
    // End of variables declaration//GEN-END:variables
}
